# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: SingerHub
email: hello@meltano.com
description: > # this means to ignore newlines until "baseurl:"
  The SingerHub is a central place to find any Singer-compatible
  tap or target. The Hub is lovingly curated by Meltano and the wider 
  Singer community.
baseurl: ""
url: "http://singerhub.io" # the base hostname & protocol for your site
twitter_username: meltanodata

collections:
  taps:
    output: true
  targets:
    output: true

defaults:
  - scope:
      path: "_targets"
    values:
      layout: "target"
      target: true

# Outputting
permalink: /:categories/:year/:month/:day/:title

# Build settings
markdown: kramdown
exclude: ["README.md"]
