[tool.poetry]
package-mode = false
description = "Meltano hub contains the definition of all meltano taps, targets, utilities, etc."
authors = ["Meltano Team"]

[tool.poetry.dependencies]
python = "^3.9"
jsonschema = "^4.17.3"
"ruamel.yaml" = "^0.18.6"
yamllint = "^1.35.1"
requests = "^2.32.3"

[tool.poetry.dev-dependencies]
black = "^24.8.0"
isort = "^5.13.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
