[tool.poetry]
name = "meltano-hub"
version = "0.1.0"
description = "Meltano hub contains the definition of all meltano taps, targets, utilities, etc."
authors = ["Meltano Team"]

[tool.poetry.dependencies]
python = "^3.9"
jsonschema = "^4.17.3"
"ruamel.yaml" = "^0.17.35"
yamllint = "^1.32.0"
requests = "^2.31.0"

[tool.poetry.dev-dependencies]
black = "^23.9.1"
isort = "^5.12.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
