definition: are files used for running your project with Docker Compose.
domain_url: https://docs.docker.com/compose/
label: Docker Compose
logo_url: /assets/logos/files/docker-compose.png
maintenance_status: active
name: files-docker-compose
namespace: files_docker_compose
pip_url: git+https://github.com/meltano/files-docker-compose.git
repo: https://github.com/meltano/files-docker-compose
variant: meltano
quality: gold
