name: files-docker-compose
label: Docker Compose
namespace: files_docker_compose
repo: https://github.com/meltano/files-docker-compose
pip_url: git+https://github.com/meltano/files-docker-compose.git
variant: meltano
logo_url: /assets/logos/files/docker-compose.png
